version: '3.1'

services:
  centos:
    build:
      context: ./
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html:Z

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: get
      MYSQL_USER: root
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: passw0rd 
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysqldatabase

volumes:
  mysql-data:
